SELECT * FROM TAB;

DROP TABLE MEMBER_TBL;

CREATE TABLE MEMBER_TBL (
	NUM		NUMBER(4),
	NAME	VARCHAR2(30),
	ID		VARCHAR2(30),
	PASS	VARCHAR2(30),
	BIRTH	NUMBER(4),
	GENDER	VARCHAR2(10),
	JOB		VARCHAR2(30),
	CITY	CHAR(10),
	JOINDATE	DATE,
	CONSTRAINT	PK_MEMBER_TBL PRIMARY KEY(NUM)
);

COMMIT

INSERT INTO MEMBER_TBL VALUES(1001, '홍길동', 'HONG1', '1234', 2002, '남자', '', '', SYSDATE);